name = "gleam_mcp"
version = "0.1.0"

description = "Gleam types and functions for building an MCP server and :wclient"
licences = ["Apache-2.0"]

repository = { type = "github", user = "adkelley", repo = "mcp_client" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
